tasks:
    - name: Install Dependencies and Start Dev Server
      init: npm install
      command: npm run dev

ports:
    - port: 5173
      onOpen: open-preview
    - port: 35729
      onOpen: ignore